// Country Geo Data: ISO3, Name, Centroid Coordinates (lat, lng), Continent, Region, Income Group
export interface CountryGeo {
  iso3: string;
  name: string;
  lat: number;
  lng: number;
  continent: string;
  un_region: string;
  income_group: string;
  flag: string;
}

export const COUNTRY_GEO_MAP: Record<string, CountryGeo> = {
  AFG: { iso3: "AFG", name: "Afghanistan", lat: 33.9391, lng: 67.7100, continent: "Asia", un_region: "South Asia", income_group: "Low income", flag: "🇦🇫" },
  ALB: { iso3: "ALB", name: "Albania", lat: 41.1533, lng: 20.1683, continent: "Europe", un_region: "Eastern Europe", income_group: "Upper middle income", flag: "🇦🇱" },
  DZA: { iso3: "DZA", name: "Algeria", lat: 28.0339, lng: 1.6596, continent: "Africa", un_region: "Northern Africa", income_group: "Lower middle income", flag: "🇩🇿" },
  ASM: { iso3: "ASM", name: "American Samoa", lat: -14.2710, lng: -170.1322, continent: "Oceania", un_region: "Polynesia", income_group: "Upper middle income", flag: "🇦🇸" },
  AND: { iso3: "AND", name: "Andorra", lat: 42.5063, lng: 1.5218, continent: "Europe", un_region: "Western Europe", income_group: "High income", flag: "🇦🇩" },
  AGO: { iso3: "AGO", name: "Angola", lat: -11.2027, lng: 17.8739, continent: "Africa", un_region: "Sub-Saharan Africa", income_group: "Lower middle income", flag: "🇦🇴" },
  AIA: { iso3: "AIA", name: "Anguilla", lat: 18.2206, lng: -63.0686, continent: "Americas", un_region: "Caribbean", income_group: "High income", flag: "🇦🇮" },
  ATG: { iso3: "ATG", name: "Antigua and Barbuda", lat: 17.0608, lng: -61.7964, continent: "Americas", un_region: "Caribbean", income_group: "High income", flag: "🇦🇬" },
  ARG: { iso3: "ARG", name: "Argentina", lat: -38.4161, lng: -63.6167, continent: "Americas", un_region: "Latin America", income_group: "Upper middle income", flag: "🇦🇷" },
  ARM: { iso3: "ARM", name: "Armenia", lat: 40.0691, lng: 45.0382, continent: "Asia", un_region: "Western Asia", income_group: "Upper middle income", flag: "🇦🇲" },
  ABW: { iso3: "ABW", name: "Aruba", lat: 12.5211, lng: -69.9683, continent: "Americas", un_region: "Caribbean", income_group: "High income", flag: "🇦🇼" },
  AUS: { iso3: "AUS", name: "Australia", lat: -25.2744, lng: 133.7751, continent: "Oceania", un_region: "Australia/NZ", income_group: "High income", flag: "🇦🇺" },
  AUT: { iso3: "AUT", name: "Austria", lat: 47.5162, lng: 14.5501, continent: "Europe", un_region: "Western Europe", income_group: "High income", flag: "🇦🇹" },
  AZE: { iso3: "AZE", name: "Azerbaijan", lat: 40.1431, lng: 47.5769, continent: "Asia", un_region: "Western Asia", income_group: "Upper middle income", flag: "🇦🇿" },
  BHS: { iso3: "BHS", name: "Bahamas", lat: 25.0343, lng: -77.3963, continent: "Americas", un_region: "Caribbean", income_group: "High income", flag: "🇧🇸" },
  BHR: { iso3: "BHR", name: "Bahrain", lat: 26.0667, lng: 50.5577, continent: "Asia", un_region: "Western Asia", income_group: "High income", flag: "🇧🇭" },
  BGD: { iso3: "BGD", name: "Bangladesh", lat: 23.6850, lng: 90.3563, continent: "Asia", un_region: "South Asia", income_group: "Lower middle income", flag: "🇧🇩" },
  BRB: { iso3: "BRB", name: "Barbados", lat: 13.1939, lng: -59.5432, continent: "Americas", un_region: "Caribbean", income_group: "High income", flag: "🇧🇧" },
  BLR: { iso3: "BLR", name: "Belarus", lat: 53.7098, lng: 27.9534, continent: "Europe", un_region: "Eastern Europe", income_group: "Upper middle income", flag: "🇧🇾" },
  BEL: { iso3: "BEL", name: "Belgium", lat: 50.5039, lng: 4.4699, continent: "Europe", un_region: "Western Europe", income_group: "High income", flag: "🇧🇪" },
  BLZ: { iso3: "BLZ", name: "Belize", lat: 17.1899, lng: -88.4976, continent: "Americas", un_region: "Central America", income_group: "Lower middle income", flag: "🇧🇿" },
  BEN: { iso3: "BEN", name: "Benin", lat: 9.3077, lng: 2.3158, continent: "Africa", un_region: "Sub-Saharan Africa", income_group: "Low income", flag: "🇧🇯" },
  BMU: { iso3: "BMU", name: "Bermuda", lat: 32.3078, lng: -64.7505, continent: "Americas", un_region: "Northern America", income_group: "High income", flag: "🇧🇲" },
  BTN: { iso3: "BTN", name: "Bhutan", lat: 27.5142, lng: 90.4336, continent: "Asia", un_region: "South Asia", income_group: "Lower middle income", flag: "🇧🇹" },
  BOL: { iso3: "BOL", name: "Bolivia", lat: -16.2902, lng: -63.5887, continent: "Americas", un_region: "Latin America", income_group: "Lower middle income", flag: "🇧🇴" },
  BIH: { iso3: "BIH", name: "Bosnia and Herzegovina", lat: 43.9159, lng: 17.6791, continent: "Europe", un_region: "Eastern Europe", income_group: "Upper middle income", flag: "🇧🇦" },
  BWA: { iso3: "BWA", name: "Botswana", lat: -22.3285, lng: 24.6849, continent: "Africa", un_region: "Sub-Saharan Africa", income_group: "Upper middle income", flag: "🇧🇼" },
  BRA: { iso3: "BRA", name: "Brazil", lat: -14.2350, lng: -51.9253, continent: "Americas", un_region: "Latin America", income_group: "Upper middle income", flag: "🇧🇷" },
  BRN: { iso3: "BRN", name: "Brunei", lat: 4.5353, lng: 114.7277, continent: "Asia", un_region: "South-Eastern Asia", income_group: "High income", flag: "🇧🇳" },
  BGR: { iso3: "BGR", name: "Bulgaria", lat: 42.7339, lng: 25.4858, continent: "Europe", un_region: "Eastern Europe", income_group: "Upper middle income", flag: "🇧🇬" },
  BFA: { iso3: "BFA", name: "Burkina Faso", lat: 12.2383, lng: -1.5616, continent: "Africa", un_region: "Sub-Saharan Africa", income_group: "Low income", flag: "🇧🇫" },
  BDI: { iso3: "BDI", name: "Burundi", lat: -3.3731, lng: 29.9189, continent: "Africa", un_region: "Sub-Saharan Africa", income_group: "Low income", flag: "🇧🇮" },
  CPV: { iso3: "CPV", name: "Cabo Verde", lat: 16.5388, lng: -23.0418, continent: "Africa", un_region: "Sub-Saharan Africa", income_group: "Lower middle income", flag: "🇨🇻" },
  KHM: { iso3: "KHM", name: "Cambodia", lat: 12.5657, lng: 104.9910, continent: "Asia", un_region: "South-Eastern Asia", income_group: "Lower middle income", flag: "🇰🇭" },
  CMR: { iso3: "CMR", name: "Cameroon", lat: 7.3697, lng: 12.3547, continent: "Africa", un_region: "Sub-Saharan Africa", income_group: "Lower middle income", flag: "🇨🇲" },
  CAN: { iso3: "CAN", name: "Canada", lat: 56.1304, lng: -106.3468, continent: "Americas", un_region: "Northern America", income_group: "High income", flag: "🇨🇦" },
  CAF: { iso3: "CAF", name: "Central African Republic", lat: 6.6111, lng: 20.9394, continent: "Africa", un_region: "Sub-Saharan Africa", income_group: "Low income", flag: "🇨🇫" },
  TCD: { iso3: "TCD", name: "Chad", lat: 15.4542, lng: 18.7322, continent: "Africa", un_region: "Sub-Saharan Africa", income_group: "Low income", flag: "🇹🇩" },
  CHL: { iso3: "CHL", name: "Chile", lat: -35.6751, lng: -71.5430, continent: "Americas", un_region: "Latin America", income_group: "High income", flag: "🇨🇱" },
  CHN: { iso3: "CHN", name: "China", lat: 35.8617, lng: 104.1954, continent: "Asia", un_region: "Eastern Asia", income_group: "Upper middle income", flag: "🇨🇳" },
  COL: { iso3: "COL", name: "Colombia", lat: 4.5709, lng: -74.2973, continent: "Americas", un_region: "Latin America", income_group: "Upper middle income", flag: "🇨🇴" },
  COM: { iso3: "COM", name: "Comoros", lat: -11.8750, lng: 43.8722, continent: "Africa", un_region: "Sub-Saharan Africa", income_group: "Low income", flag: "🇰🇲" },
  COG: { iso3: "COG", name: "Congo", lat: -0.2280, lng: 15.8277, continent: "Africa", un_region: "Sub-Saharan Africa", income_group: "Lower middle income", flag: "🇨🇬" },
  COD: { iso3: "COD", name: "DR Congo", lat: -4.0383, lng: 21.7587, continent: "Africa", un_region: "Sub-Saharan Africa", income_group: "Low income", flag: "🇨🇩" },
  CRI: { iso3: "CRI", name: "Costa Rica", lat: 9.7489, lng: -83.7534, continent: "Americas", un_region: "Latin America", income_group: "Upper middle income", flag: "🇨🇷" },
  CIV: { iso3: "CIV", name: "Côte d'Ivoire", lat: 7.5400, lng: -5.5471, continent: "Africa", un_region: "Sub-Saharan Africa", income_group: "Lower middle income", flag: "🇨🇮" },
  HRV: { iso3: "HRV", name: "Croatia", lat: 45.1000, lng: 15.2000, continent: "Europe", un_region: "Eastern Europe", income_group: "High income", flag: "🇭🇷" },
  CUB: { iso3: "CUB", name: "Cuba", lat: 21.5218, lng: -77.7812, continent: "Americas", un_region: "Latin America", income_group: "Upper middle income", flag: "🇨🇺" },
  CYP: { iso3: "CYP", name: "Cyprus", lat: 35.1264, lng: 33.4299, continent: "Europe", un_region: "Western Asia", income_group: "High income", flag: "🇨🇾" },
  CZE: { iso3: "CZE", name: "Czechia", lat: 49.8175, lng: 15.4730, continent: "Europe", un_region: "Eastern Europe", income_group: "High income", flag: "🇨🇿" },
  DNK: { iso3: "DNK", name: "Denmark", lat: 56.2639, lng: 9.5018, continent: "Europe", un_region: "Northern Europe", income_group: "High income", flag: "🇩🇰" },
  DJI: { iso3: "DJI", name: "Djibouti", lat: 11.8251, lng: 42.5903, continent: "Africa", un_region: "Sub-Saharan Africa", income_group: "Lower middle income", flag: "🇩🇯" },
  DMA: { iso3: "DMA", name: "Dominica", lat: 15.4150, lng: -61.3710, continent: "Americas", un_region: "Caribbean", income_group: "Upper middle income", flag: "🇩🇲" },
  DOM: { iso3: "DOM", name: "Dominican Republic", lat: 18.7357, lng: -70.1627, continent: "Americas", un_region: "Latin America", income_group: "Upper middle income", flag: "🇩🇴" },
  ECU: { iso3: "ECU", name: "Ecuador", lat: -1.8312, lng: -78.1834, continent: "Americas", un_region: "Latin America", income_group: "Upper middle income", flag: "🇪🇨" },
  EGY: { iso3: "EGY", name: "Egypt", lat: 26.8206, lng: 30.8025, continent: "Africa", un_region: "Northern Africa", income_group: "Lower middle income", flag: "🇪🇬" },
  SLV: { iso3: "SLV", name: "El Salvador", lat: 13.7942, lng: -88.8965, continent: "Americas", un_region: "Latin America", income_group: "Lower middle income", flag: "🇸🇻" },
  GNQ: { iso3: "GNQ", name: "Equatorial Guinea", lat: 1.6508, lng: 10.2679, continent: "Africa", un_region: "Sub-Saharan Africa", income_group: "Upper middle income", flag: "🇬🇶" },
  ERI: { iso3: "ERI", name: "Eritrea", lat: 15.1794, lng: 39.7823, continent: "Africa", un_region: "Sub-Saharan Africa", income_group: "Low income", flag: "🇪🇷" },
  EST: { iso3: "EST", name: "Estonia", lat: 58.5953, lng: 25.0136, continent: "Europe", un_region: "Northern Europe", income_group: "High income", flag: "🇪🇪" },
  SWZ: { iso3: "SWZ", name: "Eswatini", lat: -26.5225, lng: 31.4659, continent: "Africa", un_region: "Sub-Saharan Africa", income_group: "Lower middle income", flag: "🇸🇿" },
  ETH: { iso3: "ETH", name: "Ethiopia", lat: 9.1450, lng: 40.4897, continent: "Africa", un_region: "Sub-Saharan Africa", income_group: "Low income", flag: "🇪🇹" },
  FJI: { iso3: "FJI", name: "Fiji", lat: -17.7134, lng: 178.0650, continent: "Oceania", un_region: "Melanesia", income_group: "Upper middle income", flag: "🇫🇯" },
  FIN: { iso3: "FIN", name: "Finland", lat: 61.9241, lng: 25.7482, continent: "Europe", un_region: "Northern Europe", income_group: "High income", flag: "🇫🇮" },
  FRA: { iso3: "FRA", name: "France", lat: 46.2276, lng: 2.2137, continent: "Europe", un_region: "Western Europe", income_group: "High income", flag: "🇫🇷" },
  GAB: { iso3: "GAB", name: "Gabon", lat: -0.8037, lng: 11.6094, continent: "Africa", un_region: "Sub-Saharan Africa", income_group: "Upper middle income", flag: "🇬🇦" },
  GMB: { iso3: "GMB", name: "Gambia", lat: 13.4432, lng: -15.3101, continent: "Africa", un_region: "Sub-Saharan Africa", income_group: "Low income", flag: "🇬🇲" },
  GEO: { iso3: "GEO", name: "Georgia", lat: 42.3154, lng: 43.3569, continent: "Asia", un_region: "Western Asia", income_group: "Upper middle income", flag: "🇬🇪" },
  DEU: { iso3: "DEU", name: "Germany", lat: 51.1657, lng: 10.4515, continent: "Europe", un_region: "Western Europe", income_group: "High income", flag: "🇩🇪" },
  GHA: { iso3: "GHA", name: "Ghana", lat: 7.9465, lng: -1.0232, continent: "Africa", un_region: "Sub-Saharan Africa", income_group: "Lower middle income", flag: "🇬🇭" },
  GRC: { iso3: "GRC", name: "Greece", lat: 39.0742, lng: 21.8243, continent: "Europe", un_region: "Southern Europe", income_group: "High income", flag: "🇬🇷" },
  GRD: { iso3: "GRD", name: "Grenada", lat: 12.1165, lng: -61.6790, continent: "Americas", un_region: "Caribbean", income_group: "Upper middle income", flag: "🇬🇩" },
  GTM: { iso3: "GTM", name: "Guatemala", lat: 15.7835, lng: -90.2308, continent: "Americas", un_region: "Latin America", income_group: "Upper middle income", flag: "🇬🇹" },
  GIN: { iso3: "GIN", name: "Guinea", lat: 9.9456, lng: -9.6966, continent: "Africa", un_region: "Sub-Saharan Africa", income_group: "Low income", flag: "🇬🇳" },
  GNB: { iso3: "GNB", name: "Guinea-Bissau", lat: 11.8037, lng: -15.1804, continent: "Africa", un_region: "Sub-Saharan Africa", income_group: "Low income", flag: "🇬🇼" },
  GUY: { iso3: "GUY", name: "Guyana", lat: 4.8604, lng: -58.9302, continent: "Americas", un_region: "Latin America", income_group: "Upper middle income", flag: "🇬🇾" },
  HTI: { iso3: "HTI", name: "Haiti", lat: 18.9712, lng: -72.2852, continent: "Americas", un_region: "Latin America", income_group: "Low income", flag: "🇭🇹" },
  HND: { iso3: "HND", name: "Honduras", lat: 15.2000, lng: -86.2419, continent: "Americas", un_region: "Latin America", income_group: "Lower middle income", flag: "🇭🇳" },
  HKG: { iso3: "HKG", name: "Hong Kong", lat: 22.3193, lng: 114.1694, continent: "Asia", un_region: "Eastern Asia", income_group: "High income", flag: "🇭🇰" },
  HUN: { iso3: "HUN", name: "Hungary", lat: 47.1625, lng: 19.5033, continent: "Europe", un_region: "Eastern Europe", income_group: "High income", flag: "🇭🇺" },
  ISL: { iso3: "ISL", name: "Iceland", lat: 64.9631, lng: -19.0208, continent: "Europe", un_region: "Northern Europe", income_group: "High income", flag: "🇮🇸" },
  IND: { iso3: "IND", name: "India", lat: 20.5937, lng: 78.9629, continent: "Asia", un_region: "South Asia", income_group: "Lower middle income", flag: "🇮🇳" },
  IDN: { iso3: "IDN", name: "Indonesia", lat: -0.7893, lng: 113.9213, continent: "Asia", un_region: "South-Eastern Asia", income_group: "Upper middle income", flag: "🇮🇩" },
  IRN: { iso3: "IRN", name: "Iran", lat: 32.4279, lng: 53.6880, continent: "Asia", un_region: "Western Asia", income_group: "Lower middle income", flag: "🇮🇷" },
  IRQ: { iso3: "IRQ", name: "Iraq", lat: 33.2232, lng: 43.6793, continent: "Asia", un_region: "Western Asia", income_group: "Upper middle income", flag: "🇮🇶" },
  IRL: { iso3: "IRL", name: "Ireland", lat: 53.4129, lng: -8.2439, continent: "Europe", un_region: "Northern Europe", income_group: "High income", flag: "🇮🇪" },
  ISR: { iso3: "ISR", name: "Israel", lat: 31.0461, lng: 34.8516, continent: "Asia", un_region: "Western Asia", income_group: "High income", flag: "🇮🇱" },
  ITA: { iso3: "ITA", name: "Italy", lat: 41.8719, lng: 12.5674, continent: "Europe", un_region: "Southern Europe", income_group: "High income", flag: "🇮🇹" },
  JAM: { iso3: "JAM", name: "Jamaica", lat: 18.1096, lng: -77.2975, continent: "Americas", un_region: "Latin America", income_group: "Upper middle income", flag: "🇯🇲" },
  JPN: { iso3: "JPN", name: "Japan", lat: 36.2048, lng: 138.2529, continent: "Asia", un_region: "Eastern Asia", income_group: "High income", flag: "🇯🇵" },
  JOR: { iso3: "JOR", name: "Jordan", lat: 30.5852, lng: 36.2384, continent: "Asia", un_region: "Western Asia", income_group: "Upper middle income", flag: "🇯🇴" },
  KAZ: { iso3: "KAZ", name: "Kazakhstan", lat: 48.0196, lng: 66.9237, continent: "Asia", un_region: "Central Asia", income_group: "Upper middle income", flag: "🇰🇿" },
  KEN: { iso3: "KEN", name: "Kenya", lat: -0.0236, lng: 37.9062, continent: "Africa", un_region: "Sub-Saharan Africa", income_group: "Lower middle income", flag: "🇰🇪" },
  KIR: { iso3: "KIR", name: "Kiribati", lat: -3.3704, lng: -168.7340, continent: "Oceania", un_region: "Micronesia", income_group: "Lower middle income", flag: "🇰🇮" },
  PRK: { iso3: "PRK", name: "North Korea", lat: 40.3399, lng: 127.5101, continent: "Asia", un_region: "Eastern Asia", income_group: "Low income", flag: "🇰🇵" },
  KOR: { iso3: "KOR", name: "South Korea", lat: 35.9078, lng: 127.7669, continent: "Asia", un_region: "Eastern Asia", income_group: "High income", flag: "🇰🇷" },
  KWT: { iso3: "KWT", name: "Kuwait", lat: 29.3117, lng: 47.4818, continent: "Asia", un_region: "Western Asia", income_group: "High income", flag: "🇰🇼" },
  KGZ: { iso3: "KGZ", name: "Kyrgyzstan", lat: 41.2044, lng: 74.7661, continent: "Asia", un_region: "Central Asia", income_group: "Lower middle income", flag: "🇰🇬" },
  LAO: { iso3: "LAO", name: "Laos", lat: 19.8563, lng: 102.4955, continent: "Asia", un_region: "South-Eastern Asia", income_group: "Lower middle income", flag: "🇱🇦" },
  LVA: { iso3: "LVA", name: "Latvia", lat: 56.8796, lng: 24.6032, continent: "Europe", un_region: "Northern Europe", income_group: "High income", flag: "🇱🇻" },
  LBN: { iso3: "LBN", name: "Lebanon", lat: 33.8547, lng: 35.8623, continent: "Asia", un_region: "Western Asia", income_group: "Lower middle income", flag: "🇱🇧" },
  LSO: { iso3: "LSO", name: "Lesotho", lat: -29.6099, lng: 28.2336, continent: "Africa", un_region: "Sub-Saharan Africa", income_group: "Lower middle income", flag: "🇱🇸" },
  LBR: { iso3: "LBR", name: "Liberia", lat: 6.4281, lng: -9.4295, continent: "Africa", un_region: "Sub-Saharan Africa", income_group: "Low income", flag: "🇱🇷" },
  LBY: { iso3: "LBY", name: "Libya", lat: 26.3351, lng: 17.2283, continent: "Africa", un_region: "Northern Africa", income_group: "Upper middle income", flag: "🇱🇾" },
  LIE: { iso3: "LIE", name: "Liechtenstein", lat: 47.1660, lng: 9.5554, continent: "Europe", un_region: "Western Europe", income_group: "High income", flag: "🇱🇮" },
  LTU: { iso3: "LTU", name: "Lithuania", lat: 55.1694, lng: 23.8813, continent: "Europe", un_region: "Northern Europe", income_group: "High income", flag: "🇱🇹" },
  LUX: { iso3: "LUX", name: "Luxembourg", lat: 49.8153, lng: 6.1296, continent: "Europe", un_region: "Western Europe", income_group: "High income", flag: "🇱🇺" },
  MDG: { iso3: "MDG", name: "Madagascar", lat: -18.7669, lng: 46.8691, continent: "Africa", un_region: "Sub-Saharan Africa", income_group: "Low income", flag: "🇲🇬" },
  MWI: { iso3: "MWI", name: "Malawi", lat: -13.2543, lng: 34.3015, continent: "Africa", un_region: "Sub-Saharan Africa", income_group: "Low income", flag: "🇲🇼" },
  MYS: { iso3: "MYS", name: "Malaysia", lat: 4.2105, lng: 101.9758, continent: "Asia", un_region: "South-Eastern Asia", income_group: "Upper middle income", flag: "🇲🇾" },
  MDV: { iso3: "MDV", name: "Maldives", lat: 3.2028, lng: 73.2207, continent: "Asia", un_region: "South Asia", income_group: "Upper middle income", flag: "🇲🇻" },
  MLI: { iso3: "MLI", name: "Mali", lat: 17.5707, lng: -3.9962, continent: "Africa", un_region: "Sub-Saharan Africa", income_group: "Low income", flag: "🇲🇱" },
  MLT: { iso3: "MLT", name: "Malta", lat: 35.9375, lng: 14.3754, continent: "Europe", un_region: "Southern Europe", income_group: "High income", flag: "🇲🇹" },
  MHL: { iso3: "MHL", name: "Marshall Islands", lat: 7.1315, lng: 171.1845, continent: "Oceania", un_region: "Micronesia", income_group: "Upper middle income", flag: "🇲🇭" },
  MRT: { iso3: "MRT", name: "Mauritania", lat: 21.0079, lng: -10.9408, continent: "Africa", un_region: "Sub-Saharan Africa", income_group: "Lower middle income", flag: "🇲🇷" },
  MUS: { iso3: "MUS", name: "Mauritius", lat: -20.3484, lng: 57.5522, continent: "Africa", un_region: "Sub-Saharan Africa", income_group: "High income", flag: "🇲🇺" },
  MEX: { iso3: "MEX", name: "Mexico", lat: 23.6345, lng: -102.5528, continent: "Americas", un_region: "Latin America", income_group: "Upper middle income", flag: "🇲🇽" },
  FSM: { iso3: "FSM", name: "Micronesia", lat: 7.4256, lng: 150.5508, continent: "Oceania", un_region: "Micronesia", income_group: "Lower middle income", flag: "🇫🇲" },
  MDA: { iso3: "MDA", name: "Moldova", lat: 47.4116, lng: 28.3699, continent: "Europe", un_region: "Eastern Europe", income_group: "Lower middle income", flag: "🇲🇩" },
  MCO: { iso3: "MCO", name: "Monaco", lat: 43.7384, lng: 7.4246, continent: "Europe", un_region: "Western Europe", income_group: "High income", flag: "🇲🇨" },
  MNG: { iso3: "MNG", name: "Mongolia", lat: 46.8625, lng: 103.8467, continent: "Asia", un_region: "Eastern Asia", income_group: "Lower middle income", flag: "🇲🇳" },
  MNE: { iso3: "MNE", name: "Montenegro", lat: 42.7087, lng: 19.3744, continent: "Europe", un_region: "Eastern Europe", income_group: "Upper middle income", flag: "🇲🇪" },
  MAR: { iso3: "MAR", name: "Morocco", lat: 31.7917, lng: -7.0926, continent: "Africa", un_region: "Northern Africa", income_group: "Lower middle income", flag: "🇲🇦" },
  MOZ: { iso3: "MOZ", name: "Mozambique", lat: -18.6657, lng: 35.5296, continent: "Africa", un_region: "Sub-Saharan Africa", income_group: "Low income", flag: "🇲🇿" },
  MMR: { iso3: "MMR", name: "Myanmar", lat: 21.9162, lng: 95.9560, continent: "Asia", un_region: "South-Eastern Asia", income_group: "Lower middle income", flag: "🇲🇲" },
  NAM: { iso3: "NAM", name: "Namibia", lat: -22.9576, lng: 18.4904, continent: "Africa", un_region: "Sub-Saharan Africa", income_group: "Upper middle income", flag: "🇳🇦" },
  NRU: { iso3: "NRU", name: "Nauru", lat: -0.5228, lng: 166.9315, continent: "Oceania", un_region: "Micronesia", income_group: "High income", flag: "🇳🇷" },
  NPL: { iso3: "NPL", name: "Nepal", lat: 28.3949, lng: 84.1240, continent: "Asia", un_region: "South Asia", income_group: "Lower middle income", flag: "🇳🇵" },
  NLD: { iso3: "NLD", name: "Netherlands", lat: 52.1326, lng: 5.2913, continent: "Europe", un_region: "Western Europe", income_group: "High income", flag: "🇳🇱" },
  NZL: { iso3: "NZL", name: "New Zealand", lat: -40.9006, lng: 174.8860, continent: "Oceania", un_region: "Australia/NZ", income_group: "High income", flag: "🇳🇿" },
  NIC: { iso3: "NIC", name: "Nicaragua", lat: 12.8654, lng: -85.2072, continent: "Americas", un_region: "Latin America", income_group: "Lower middle income", flag: "🇳🇮" },
  NER: { iso3: "NER", name: "Niger", lat: 17.6078, lng: 8.0817, continent: "Africa", un_region: "Sub-Saharan Africa", income_group: "Low income", flag: "🇳🇪" },
  NGA: { iso3: "NGA", name: "Nigeria", lat: 9.0820, lng: 8.6753, continent: "Africa", un_region: "Sub-Saharan Africa", income_group: "Lower middle income", flag: "🇳🇬" },
  MKD: { iso3: "MKD", name: "North Macedonia", lat: 41.6086, lng: 21.7453, continent: "Europe", un_region: "Eastern Europe", income_group: "Upper middle income", flag: "🇲🇰" },
  NOR: { iso3: "NOR", name: "Norway", lat: 60.4720, lng: 8.4689, continent: "Europe", un_region: "Northern Europe", income_group: "High income", flag: "🇳🇴" },
  OMN: { iso3: "OMN", name: "Oman", lat: 21.5126, lng: 55.9233, continent: "Asia", un_region: "Western Asia", income_group: "High income", flag: "🇴🇲" },
  PAK: { iso3: "PAK", name: "Pakistan", lat: 30.3753, lng: 69.3451, continent: "Asia", un_region: "South Asia", income_group: "Lower middle income", flag: "🇵🇰" },
  PLW: { iso3: "PLW", name: "Palau", lat: 7.5150, lng: 134.5825, continent: "Oceania", un_region: "Micronesia", income_group: "High income", flag: "🇵🇼" },
  PSE: { iso3: "PSE", name: "Palestine", lat: 31.9522, lng: 35.2332, continent: "Asia", un_region: "Western Asia", income_group: "Lower middle income", flag: "🇵🇸" },
  PAN: { iso3: "PAN", name: "Panama", lat: 8.5379, lng: -80.7821, continent: "Americas", un_region: "Latin America", income_group: "High income", flag: "🇵🇦" },
  PNG: { iso3: "PNG", name: "Papua New Guinea", lat: -6.3150, lng: 143.9555, continent: "Oceania", un_region: "Melanesia", income_group: "Lower middle income", flag: "🇵🇬" },
  PRY: { iso3: "PRY", name: "Paraguay", lat: -23.4425, lng: -58.4438, continent: "Americas", un_region: "Latin America", income_group: "Upper middle income", flag: "🇵🇾" },
  PER: { iso3: "PER", name: "Peru", lat: -9.1900, lng: -75.0152, continent: "Americas", un_region: "Latin America", income_group: "Upper middle income", flag: "🇵🇪" },
  PHL: { iso3: "PHL", name: "Philippines", lat: 12.8797, lng: 121.7740, continent: "Asia", un_region: "South-Eastern Asia", income_group: "Lower middle income", flag: "🇵🇭" },
  POL: { iso3: "POL", name: "Poland", lat: 51.9194, lng: 19.1451, continent: "Europe", un_region: "Eastern Europe", income_group: "High income", flag: "🇵🇱" },
  PRT: { iso3: "PRT", name: "Portugal", lat: 39.3999, lng: -8.2245, continent: "Europe", un_region: "Southern Europe", income_group: "High income", flag: "🇵🇹" },
  PRI: { iso3: "PRI", name: "Puerto Rico", lat: 18.2208, lng: -66.5901, continent: "Americas", un_region: "Latin America", income_group: "High income", flag: "🇵🇷" },
  QAT: { iso3: "QAT", name: "Qatar", lat: 25.3548, lng: 51.1839, continent: "Asia", un_region: "Western Asia", income_group: "High income", flag: "🇶🇦" },
  ROU: { iso3: "ROU", name: "Romania", lat: 45.9432, lng: 24.9668, continent: "Europe", un_region: "Eastern Europe", income_group: "High income", flag: "🇷🇴" },
  RUS: { iso3: "RUS", name: "Russia", lat: 61.5240, lng: 105.3188, continent: "Europe", un_region: "Eastern Europe", income_group: "Upper middle income", flag: "🇷🇺" },
  RWA: { iso3: "RWA", name: "Rwanda", lat: -1.9403, lng: 29.8739, continent: "Africa", un_region: "Sub-Saharan Africa", income_group: "Low income", flag: "🇷🇼" },
  KNA: { iso3: "KNA", name: "Saint Kitts and Nevis", lat: 17.3578, lng: -62.7830, continent: "Americas", un_region: "Latin America", income_group: "High income", flag: "🇰🇳" },
  LCA: { iso3: "LCA", name: "Saint Lucia", lat: 13.9094, lng: -60.9789, continent: "Americas", un_region: "Latin America", income_group: "Upper middle income", flag: "🇱🇨" },
  VCT: { iso3: "VCT", name: "Saint Vincent", lat: 12.9843, lng: -61.2872, continent: "Americas", un_region: "Caribbean", income_group: "Upper middle income", flag: "🇻🇨" },
  WSM: { iso3: "WSM", name: "Samoa", lat: -13.7590, lng: -172.1046, continent: "Oceania", un_region: "Polynesia", income_group: "Lower middle income", flag: "🇼🇸" },
  SMR: { iso3: "SMR", name: "San Marino", lat: 43.9424, lng: 12.4578, continent: "Europe", un_region: "Southern Europe", income_group: "High income", flag: "🇸🇲" },
  STP: { iso3: "STP", name: "Sao Tome and Principe", lat: 0.1864, lng: 6.6131, continent: "Africa", un_region: "Sub-Saharan Africa", income_group: "Lower middle income", flag: "🇸🇹" },
  SAU: { iso3: "SAU", name: "Saudi Arabia", lat: 23.8859, lng: 45.0792, continent: "Asia", un_region: "Western Asia", income_group: "High income", flag: "🇸🇦" },
  SEN: { iso3: "SEN", name: "Senegal", lat: 14.4974, lng: -14.4524, continent: "Africa", un_region: "Sub-Saharan Africa", income_group: "Lower middle income", flag: "🇸🇳" },
  SRB: { iso3: "SRB", name: "Serbia", lat: 44.0165, lng: 21.0059, continent: "Europe", un_region: "Eastern Europe", income_group: "Upper middle income", flag: "🇷🇸" },
  SYC: { iso3: "SYC", name: "Seychelles", lat: -4.6796, lng: 55.4920, continent: "Africa", un_region: "Sub-Saharan Africa", income_group: "High income", flag: "🇸🇨" },
  SLE: { iso3: "SLE", name: "Sierra Leone", lat: 8.4606, lng: -11.7799, continent: "Africa", un_region: "Sub-Saharan Africa", income_group: "Low income", flag: "🇸🇱" },
  SGP: { iso3: "SGP", name: "Singapore", lat: 1.3521, lng: 103.8198, continent: "Asia", un_region: "South-Eastern Asia", income_group: "High income", flag: "🇸🇬" },
  SVK: { iso3: "SVK", name: "Slovakia", lat: 48.6690, lng: 19.6990, continent: "Europe", un_region: "Eastern Europe", income_group: "High income", flag: "🇸🇰" },
  SVN: { iso3: "SVN", name: "Slovenia", lat: 46.1512, lng: 14.9955, continent: "Europe", un_region: "Eastern Europe", income_group: "High income", flag: "🇸🇮" },
  SLB: { iso3: "SLB", name: "Solomon Islands", lat: -9.6457, lng: 160.1562, continent: "Oceania", un_region: "Melanesia", income_group: "Lower middle income", flag: "🇸🇧" },
  SOM: { iso3: "SOM", name: "Somalia", lat: 5.1521, lng: 46.1996, continent: "Africa", un_region: "Sub-Saharan Africa", income_group: "Low income", flag: "🇸🇴" },
  ZAF: { iso3: "ZAF", name: "South Africa", lat: -30.5595, lng: 22.9375, continent: "Africa", un_region: "Sub-Saharan Africa", income_group: "Upper middle income", flag: "🇿🇦" },
  SSD: { iso3: "SSD", name: "South Sudan", lat: 6.8770, lng: 31.3070, continent: "Africa", un_region: "Sub-Saharan Africa", income_group: "Low income", flag: "🇸🇸" },
  ESP: { iso3: "ESP", name: "Spain", lat: 40.4637, lng: -3.7492, continent: "Europe", un_region: "Southern Europe", income_group: "High income", flag: "🇪🇸" },
  LKA: { iso3: "LKA", name: "Sri Lanka", lat: 7.8731, lng: 80.7718, continent: "Asia", un_region: "South Asia", income_group: "Lower middle income", flag: "🇱🇰" },
  SDN: { iso3: "SDN", name: "Sudan", lat: 12.8628, lng: 30.2176, continent: "Africa", un_region: "Sub-Saharan Africa", income_group: "Low income", flag: "🇸🇩" },
  SUR: { iso3: "SUR", name: "Suriname", lat: 3.9193, lng: -56.0278, continent: "Americas", un_region: "Latin America", income_group: "Upper middle income", flag: "🇸🇷" },
  SWE: { iso3: "SWE", name: "Sweden", lat: 60.1282, lng: 18.6435, continent: "Europe", un_region: "Northern Europe", income_group: "High income", flag: "🇸🇪" },
  CHE: { iso3: "CHE", name: "Switzerland", lat: 46.8182, lng: 8.2275, continent: "Europe", un_region: "Western Europe", income_group: "High income", flag: "🇨🇭" },
  SYR: { iso3: "SYR", name: "Syria", lat: 34.8021, lng: 38.9968, continent: "Asia", un_region: "Western Asia", income_group: "Low income", flag: "🇸🇾" },
  TWN: { iso3: "TWN", name: "Taiwan", lat: 23.6978, lng: 120.9605, continent: "Asia", un_region: "Eastern Asia", income_group: "High income", flag: "🇹🇼" },
  TJK: { iso3: "TJK", name: "Tajikistan", lat: 38.8610, lng: 71.2761, continent: "Asia", un_region: "Central Asia", income_group: "Low income", flag: "🇹🇯" },
  TZA: { iso3: "TZA", name: "Tanzania", lat: -6.3690, lng: 34.8888, continent: "Africa", un_region: "Sub-Saharan Africa", income_group: "Lower middle income", flag: "🇹🇿" },
  THA: { iso3: "THA", name: "Thailand", lat: 15.8700, lng: 100.9925, continent: "Asia", un_region: "South-Eastern Asia", income_group: "Upper middle income", flag: "🇹🇭" },
  TLS: { iso3: "TLS", name: "Timor-Leste", lat: -8.8742, lng: 125.7275, continent: "Asia", un_region: "South-Eastern Asia", income_group: "Lower middle income", flag: "🇹🇱" },
  TGO: { iso3: "TGO", name: "Togo", lat: 8.6195, lng: 0.8248, continent: "Africa", un_region: "Sub-Saharan Africa", income_group: "Low income", flag: "🇹🇬" },
  TON: { iso3: "TON", name: "Tonga", lat: -21.1789, lng: -175.1982, continent: "Oceania", un_region: "Polynesia", income_group: "Upper middle income", flag: "🇹🇴" },
  TTO: { iso3: "TTO", name: "Trinidad and Tobago", lat: 10.6918, lng: -61.2225, continent: "Americas", un_region: "Latin America", income_group: "High income", flag: "🇹🇹" },
  TUN: { iso3: "TUN", name: "Tunisia", lat: 33.8869, lng: 9.5375, continent: "Africa", un_region: "Northern Africa", income_group: "Lower middle income", flag: "🇹🇳" },
  TUR: { iso3: "TUR", name: "Turkey", lat: 38.9637, lng: 35.2433, continent: "Asia", un_region: "Western Asia", income_group: "Upper middle income", flag: "🇹🇷" },
  TKM: { iso3: "TKM", name: "Turkmenistan", lat: 38.9697, lng: 59.5563, continent: "Asia", un_region: "Central Asia", income_group: "Upper middle income", flag: "🇹🇲" },
  TUV: { iso3: "TUV", name: "Tuvalu", lat: -7.1095, lng: 177.6493, continent: "Oceania", un_region: "Polynesia", income_group: "Upper middle income", flag: "🇹🇻" },
  UGA: { iso3: "UGA", name: "Uganda", lat: 1.3733, lng: 32.2903, continent: "Africa", un_region: "Sub-Saharan Africa", income_group: "Low income", flag: "🇺🇬" },
  UKR: { iso3: "UKR", name: "Ukraine", lat: 48.3794, lng: 31.1656, continent: "Europe", un_region: "Eastern Europe", income_group: "Lower middle income", flag: "🇺🇦" },
  ARE: { iso3: "ARE", name: "United Arab Emirates", lat: 23.4241, lng: 53.8478, continent: "Asia", un_region: "Western Asia", income_group: "High income", flag: "🇦🇪" },
  GBR: { iso3: "GBR", name: "United Kingdom", lat: 55.3781, lng: -3.4360, continent: "Europe", un_region: "Northern Europe", income_group: "High income", flag: "🇬🇧" },
  USA: { iso3: "USA", name: "United States", lat: 37.0902, lng: -95.7129, continent: "Americas", un_region: "Northern America", income_group: "High income", flag: "🇺🇸" },
  URY: { iso3: "URY", name: "Uruguay", lat: -32.5228, lng: -55.7658, continent: "Americas", un_region: "Latin America", income_group: "High income", flag: "🇺🇾" },
  UZB: { iso3: "UZB", name: "Uzbekistan", lat: 41.3775, lng: 64.5853, continent: "Asia", un_region: "Central Asia", income_group: "Lower middle income", flag: "🇺🇿" },
  VUT: { iso3: "VUT", name: "Vanuatu", lat: -15.3767, lng: 166.9592, continent: "Oceania", un_region: "Melanesia", income_group: "Lower middle income", flag: "🇻🇺" },
  VEN: { iso3: "VEN", name: "Venezuela", lat: 6.4238, lng: -66.5897, continent: "Americas", un_region: "Latin America", income_group: "Lower middle income", flag: "🇻🇪" },
  VNM: { iso3: "VNM", name: "Vietnam", lat: 14.0583, lng: 108.2772, continent: "Asia", un_region: "South-Eastern Asia", income_group: "Lower middle income", flag: "🇻🇳" },
  YEM: { iso3: "YEM", name: "Yemen", lat: 15.5527, lng: 48.5164, continent: "Asia", un_region: "Western Asia", income_group: "Low income", flag: "🇾🇪" },
  ZMB: { iso3: "ZMB", name: "Zambia", lat: -13.1339, lng: 27.8493, continent: "Africa", un_region: "Sub-Saharan Africa", income_group: "Lower middle income", flag: "🇿🇲" },
  ZWE: { iso3: "ZWE", name: "Zimbabwe", lat: -19.0154, lng: 29.1549, continent: "Africa", un_region: "Sub-Saharan Africa", income_group: "Low income", flag: "🇿🇼" }
};

export function getCountryGeo(iso3: string): CountryGeo {
  if (COUNTRY_GEO_MAP[iso3]) return COUNTRY_GEO_MAP[iso3];
  return {
    iso3,
    name: iso3,
    lat: 0,
    lng: 0,
    continent: "Unknown",
    un_region: "Unknown",
    income_group: "Unknown",
    flag: "🌐"
  };
}

// Convert Lat/Lng to normalized Map Projection Coordinates (0 to 1000 width, 0 to 500 height)
export function projectLatLng(lat: number, lng: number, width: number = 1000, height: number = 500): { x: number; y: number } {
  const x = ((lng + 180) / 360) * width;
  const clampedLat = Math.max(-85, Math.min(85, lat));
  const y = ((90 - clampedLat) / 180) * height;
  return { x: Math.max(8, Math.min(width - 8, x)), y: Math.max(8, Math.min(height - 8, y)) };
}

